CREATE DATABASE IF NOT EXISTS IT_Support_Bot;
USE IT_Support_Bot;

CREATE TABLE IF NOT EXISTS incidents (
    id INT AUTO_INCREMENT PRIMARY KEY,
    server_name VARCHAR(255),
    error_msg TEXT,
    severity VARCHAR(50),
    ai_fix TEXT,
    status VARCHAR(50) DEFAULT 'QUEUED', 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);